### ISSUE TITLE
[common] Projects 칸반 설정

### ISSUE THREAD

**Issue by mon823** [bluepa/bluepa-rental#3]
## :bulb: 이슈 내용
- 칸반 하나로 하기로 했자나

## :white_check_mark: 작업 내용
- [x] 칸반 하나로 수정하기

**Comment by zxcv859500** [comment]
그럼 common 하나로 묶는걸로?

**Comment by mon823** [comment]
> 그럼 common 하나로 묶는걸로?

DEV 관련 칸반으로 하나 묶어

**Comment by zxcv859500** [comment]
BE를 Dev로 바꾸고 FE는 삭제했음
