### ISSUE TITLE
[FE] 로그인 UX/UI 

### ISSUE THREAD

**Issue by YaeheeChoe** [bluepa/bluepa-rental#60]
## 이슈 내용
- 로그인 UX/UI 제안
![KakaoTalk_20210402_153302959](https://user-images.githubusercontent.com/72256237/113389259-ae302600-93ca-11eb-9627-640d624539f3.jpg)
![KakaoTalk_20210402_152319871](https://user-images.githubusercontent.com/72256237/113389266-b1c3ad00-93ca-11eb-91ac-a1b29082aedb.jpg)
![KakaoTalk_20210402_153355340](https://user-images.githubusercontent.com/72256237/113389270-b2f4da00-93ca-11eb-8212-c7f982dd0140.jpg)
![KakaoTalk_20210402_153431063](https://user-images.githubusercontent.com/72256237/113389274-b5efca80-93ca-11eb-8712-ecd0ce4d0056.jpg)

## 작업 내용
- [ ] StartScreen 에 슬라이더 및 애니메이션 추가
- [ ] 애니메이션 추가

## 주의 사항
1.  시작페이지 : 슬라이더 및 애니메이션, 버튼
2. 시작버튼 클릭 시 아래에서 버튼 포함된 Drawer튀어나옴
3. 이메일로 계속 클릭 시 이메일 입력. 이메일 회원가입 페이지 -> 이메일로 코드를 보내 로그인하는게 기본인데 이렇게 할까?
4. 이미 계정이 있을 시 비밀번호 로그인 가능
5. 사진엔 안보이나 제목 등에 애니메이션이 포함되어 있음. 고급져보이므로 넣는 것이 좋아보임
- 그리고 백엔드 어케 연동해야할지 모르겠음

**Comment by zxcv859500** [comment]
백엔드 연동은 아직 신경쓰지않는게 좋을듯
